apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    name: hello-app
    type: frontend

spec:
  containers:
    - name: hello-app
      image: nigelpoulton/k8sbook:latest
      ports:
        - containerPort: 8080
